### ISSUE TITLE
Animator

### ISSUE THREAD

**Issue by git-cgalan** [iGEM-Bettencourt-2021/Dry-lab#14]
### The animator

They will be in charge of **the interactive and animated elements** of the wiki.

The key point to enjoy a well designed website is to make it dynamic so that it's able to captivate he attention of the visitor. We will need a diversity of interactive elements to facilitate the navigation in the website and also animations to make it more dynamic. The difficulty is to implement animation on the text and the images that fits to the design, not too much, neither too few.

They will be answering the questions how to make this page more attractive and dynamic.

The requirements for this role will be to have a creativity, basis in Javascript, very basis of CSS

**Comment by jeanrannou** [comment]
I wish to help here but my knowledge is pretty low. We're going to use bootstrap right ?
