### ISSUE TITLE
shaper tasks 01/05 - 07/05

### ISSUE THREAD

**Issue by git-cgalan** [iGEM-Bettencourt-2021/Dry-lab#19]
**objectives**

- Develop a model of the website (starting with the Team page) 
- Designing the tab bar 
- If we have access to the website, start the structure

**Comment by camilaball** [comment]
First shaper meeting 04/05/2021 Juliette - Jean - Camila

During this meeting we talked about: 
-Figma: how it could be an easy mockup/model for our wiki to have the visual aspects of our wiki
-On iGEM we have access to the HTML database but not the whole code
-Figma tutorial (be careful that the figma template isn’t too complicated to then code it :/) 

We have to focus first on the team members page for our wiki

To do after meeting: 
-Start using Figma, https://www.figma.com/team_invite/redeem/hhKTXKIKLtYJkLD6zVB7E4, try to stick to the theme (colors from instagram) and start shaping the website 
-Ask alumnis their whole code for their wiki
-Ask the alumnis how they created their wiki
-Have a meeting with past igem team members how they organised their wiki

**Comment by camilaball** [comment]
I'm sorry this is not a very nicely written summary the next ones will look better
