### ISSUE TITLE
Dry-lab general meeting - 03/19/21 at 6pm -

### ISSUE THREAD

**Issue by git-cgalan** [iGEM-Bettencourt-2021/Dry-lab#6]
Hey All @iGEM-Bettencourt-2021/dry-lab-data-analysis, 

As we discussed, the 2nd team meeting will occur on Friday this week and will be organised by @git-cgalan.
It will be a general meeting with the whole team to discuss about our following objectives. 

During this event, the following point will be addressed : 

   - Table round of each member feelings and achievements since last general meeting
   - Discussion about the skills and the associated roles
   - Volunteer repartition of tasks and learning assignments
   - brainstorming about project ideas, objectives and the associated requirements
   - discussion about internal organization of Dry-lab

I hope that every Dry-lab member will be able to participate to this meeting and I will add that all the @iGEM-Bettencourt-2021/whole-team members are also welcome to attend.

Any suggestions? write them in the comments 😉  

See you on Friday

**Comment by nathaliaraquelx** [comment]
I'm sorry, I won't be able to attend this one. My lab usually does meetings on Fridays (at this exact time).

**Comment by JulianQ22** [comment]
I have classes until 7pm, thus it's not the best time for me, I would have prefered 7-8pm but I can try mute my lecture to attend the meeting ... (if there is no other solution)

**Comment by jeanrannou** [comment]
Hi guys, again so sorry for being absent during last dry lab's meeting. I will be of course present tomorrow :)
