### ISSUE TITLE
Weekly update 

### ISSUE THREAD

**Issue by git-cgalan** [iGEM-Bettencourt-2021/Dry-lab#8]
Comment below what you did/learnt this week before the meeting on Friday.

**Comment by research555** [comment]
Where are the updates?

**Comment by KangkanS** [comment]
Learned about css from w3schools and a youtube course. Roughly an hour into the youtube course, learning about different colours and how to use text colours. The animation portion of the course starts at around 4 hours. 

w3schools link: https://www.w3schools.com/css/css_colors.asp
youtube course link: https://www.youtube.com/watch?v=1Rs2ND1ryYc

**Comment by git-cgalan** [comment]
Read almost everything about the wiki on the igem webpage. [https://2020.igem.org/Competition/Deliverables/Wiki](url)
Look at several wiki page to get inspiration for the construction of our own wiki page.
Found 2/3 relevant ressources for the website development 
Created documents in order to organize the the website design and form. 
Partially made an intro to the collab (jupyter lab interface) for the team (to be completed)

**Comment by JulietteB-cri** [comment]
Week of the 5th of April:
- Start watching iGEM Academia Wiki youtube tutorials: https://www.youtube.com/watch?v=Yrwcet6VN1Y&list=PLtm62lN7LuqihD4-ixuc2Z3lb1PyR9ENJ
- Looking at other IGEMs teams wikis and the different sections present in their websites. 
- Scikit-learn: test &train set, random forests, decision trees

**Comment by nathaliaraquelx** [comment]
Week of 5th of April:

- Filled "_the wiki_" document with a few ideas;
- Looked at the nominees and winners of the best wiki prize;
- Finishing a course on JS and watching the iGEM Foundation videos sent by Abhay;

**Comment by AbhayKoushik** [comment]
Week of 5th April:
- Google Colab Tutorial for Clement, feel free to reach out to any of us if you have issues using Google's [**Colab**](colab.research.google.com) or CRI's **[Jupyter Notebook](https://jupyter.cri-paris.org/)**

**Comment by JulianQ22** [comment]
Week of 12th April:

- Started digging into CSS tools besides Bootstrap : Flexbox and Grid. Might be really useful for the _Shapers_ (wiki development role) as it is an easier way to organize and build the framework/structure of the wiki
   https://www.freecodecamp.org/news/web-development-2020/
   https://www.educba.com/flexbox-vs-bootstrap/
   But still need to figure out their range of action and how we could use them for our wiki. 
- Filled the wiki with funky stuff (not core I mean)
- Look out for basic competence needed for the illustrators (another wiki development role) : https://bluesteelesolutions.com/graphic-design-rules/#:~:text=Be%20consistent%20with%20the%20following,stick%20to%201%20font%20family

**Comment by JulietteB-cri** [comment]
Week of 5th & 12th of April:

Completed the google doc "wiki" with ideas 
iGEM academy videos on wiki design

**Comment by jeanrannou** [comment]
Week of 12th of April:
- Benchmarked some iGEM wikis and technos used
- Prepared a demo of Adobe XD (that I have to do this week)

**Comment by KaroGu** [comment]
Week of 12th April:

- Watched iGEM Academia Wiki videos
- Looked at the requirements for the medals at https://2021.igem.org/Judging/Medals
- Filled "the wiki" doc with some ideas, added some of the missing categories and their required URLs. Additionally, looked at some of the different categories of the previous wikis and added a few links as good examples

**Comment by camilaball** [comment]
Week of 18th April: 

- igem academy wiki videos 
- Added some ideas on wiki doc

**Comment by jeanrannou** [comment]
Week of 18th April:
Wiki:
- Watched iGEM wiki videos (how to Wiki)
- Posted ideas and suggestions on the google docs
- Prepared a demo for Adobe XD

Other:
- Posted the 1st LinkedIn post
